services:
  - type: web
    name: squadup-backend
    env: node
    plan: free
    repo: https://github.com/M4kuro/CSTP-2204-SquadUP
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
